export enum Types {
  TOGGLE_CART_HIDDEN = '@cart/TOGGLE_CART_HIDDEN',
  ADD_CART_ITEM = '@cart/ADD_CART_ITEM',
  REMOVE_CART_ITEM = '@cart/REMOVE_CART_ITEM',
  CLEAR_CART_ITEM = '@cart/CLEAR_CART_ITEM',

  CLEAR_CART = '@card/CLEAR_CART',
}
