export enum Types {
  GOOGLE_SIGN_IN_REQUEST = '@user/GOOGLE_SIGN_IN',
  EMAIL_SIGN_IN_REQUEST = '@user/EMAIL_SIGN_IN',

  SIGN_IN_SUCCESS = '@user/GOOGLE_SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE = '@user/GOOGLE_SIGN_IN_FAILURE',
}
