export enum Types {
  FETCH_COLLECTIONS_REQUEST = 'SHOP/FETCH_COLLECTIONS_REQUEST',
  FETCH_COLLECTIONS_SUCCESS = 'SHOP/FETCH_COLLECTIONS_SUCCESS',
  FETCH_COLLECTIONS_FAILURE = 'SHOP/FETCH_COLLECTIONS_FAILURE',
}
